GET http://localhost:3000/api/categorias

###

GET http://localhost:3000/api/categorias/2

###

POST http://localhost:3000/api/categorias
{
    "nombre": "Categoría de prueba"
}

###

PUT http://localhost:3000/api/categorias/16
Content-Type: application/json

{
    "categoria_id": 17,
    "nombre": "Categoría de prueba editada"
}

###

DELETE http://localhost:3000/api/categorias/17

```